### ISSUE TITLE
[Bug]:  It keeps crashing i cant even load it keep giveing an erro code

### ISSUE THREAD

**Issue by Urmom232** [TeamLapen/Werewolves#108]
### Minecraft Version

1.18.x

### Forge Version

1

### Vampirism Version

1

### Werewolves Version

1.18.2

### Modpack

the werewolf mod

### Singleplayer/Multiplayer

Both

### What happened?

It keeps crashing i cant even load it keep giveing an erro code

### Relevant log output

```bash
f
```

### Reproduce steps

f

### Other relevant mods

e

**Comment by Cheaterpaul** [comment]
Without any information i can not help you. Checkout https://teamlapen.github.io/Werewolves/docs/wiki/troubleshooting#javalangincompatibleclasschangeerror

**Comment by ricvic79** [comment]
Having same issue:

The game crashed whilst rendering overlay
Error: java.lang.IncompatibleClassChangeError: class de.teamlapen.werewolves.client.model.geom.InvisibleModelPart cannot inherit from final class net.minecraft.client.model.geom.ModelPart
Exit Code: -1

**Comment by Cheaterpaul** [comment]
read the linked paragraph for a fix
