### ISSUE TITLE
[Bug]: crash with newer version of mca-reborn

### ISSUE THREAD

**Issue by dher383** [TeamLapen/Werewolves#119]
### Minecraft Version

1.18.x

### Forge Version

40.1.73

### Vampirism Version

1.8.5

### Werewolves Version

0.6.1

### Singleplayer/Multiplayer

Singleplayer

### What happened?

My game crashes during starting up when using the mod version:7.3.19 of mca-reborn.
And here's crash-report:
[crash-2022-08-24_10.41.57-client.txt](https://github.com/TeamLapen/Werewolves/files/9412087/crash-2022-08-24_10.41.57-client.txt)

### Reproduce steps

1.update the mca-reborn mod version to 7.3.19
2.launch game
3.crash when starting up

### Other relevant mods

[minecraft-comes-alive-7.3.19+1.18.2-universal.jar](https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn)

**Comment by Cheaterpaul** [comment]
This is an issue of Vampirism integration with MCA Reborn. Please update Vampirism integration to the newest alpha Version
