### ISSUE TITLE
[Bug]: Crash on startup

### ISSUE THREAD

**Issue by festro** [TeamLapen/Werewolves#129]
### Minecraft Version

1.16.x

### Forge Version

36.2.39

### Vampirism Version

1.9.0-beta.1

### Werewolves Version

1.0.0.0

### Singleplayer/Multiplayer

Both

### What happened?

Upon launching will go through the loading phase, after getting to a certain point will soft crafh "pull you to an in-game window that tells you what mod crashed", Here's the log
[crash-2022-10-12_22.25.53-fml.txt](https://github.com/TeamLapen/Werewolves/files/9771120/crash-2022-10-12_22.25.53-fml.txt)

**Comment by Cheaterpaul** [comment]
Werewolves 1.0.0.0 requires Vampirism 1.8. If you want to use Vampirism 1.9 use the Werewolves 1.1.0.0-beta.1

**Comment by festro** [comment]
Ok thanks.
