### ISSUE TITLE
1.19.2 Ore Gen

### ISSUE THREAD

**Issue by Daihok41** [TeamLapen/Werewolves#130]
### What?

The 1.19.2 ore gen in config dont work you cant disable it. I would like to see this fixed cause the ore generates everywhere. The tools from the mod is better then iron and seeing the ore generates everywhere seems a little OP IMO.

### Mod experience

I would say fix the ore gen option or making ore the more rare would balance the mod more. Maybe make it so the ore doesnt spawn on the surface at all.

**Comment by Cheaterpaul** [comment]
Starting with 1.19 features such as workgen can only be changed via datapacks.

You can modify the `werewolves:has_gen/silver_ore` biome tag to specify the biomes in which silver ore can spawn.

The silver ore frequency is not yet optimal

**Comment by Cheaterpaul** [comment]
It is rare now and the frequency can be modified in the common config.
