### ISSUE TITLE
[Bug]: 1.19.2 Crash on launch

### ISSUE THREAD

**Issue by Hexblood** [TeamLapen/Werewolves#131]
### Minecraft Version

1.18.x

### Forge Version

43.1.43

### Werewolves Version

1.0.0.0

### Modpack

Custom

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Crashed during launch.

### Relevant log output

```bash
Crash Report: https://pastebin.com/jrLnf123
Debug Log: https://paste.ee/p/wJlzM
Latest Log: https://paste.ee/p/1o9G1
```

### Reproduce steps

All I did is launch a custom pack with Werewolves included.

**Comment by Cheaterpaul** [comment]
`net.minecraftforge.fml.ModLoadingException: Mod framedcompactdrawers requires storagedrawers 11.1.1 or above
Currently, storagedrawers is 10.2.1`
