### ISSUE TITLE
Feature Enhancement: MORE FOOD (1.16.5 and forward)

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [TeamLapen/Werewolves#132]
I've spent the last two days making an **extensive** food list for exceptions to add for werewolves to eat in 1.16.5 and 1.18.2. Would love to see these foods marked as meat?

1.16.5: 
customMeatItems = ["occultism:datura", "ars_nouveau:mana_berry", "artifacts:eternal_steak", "upgrade_aquatic:cooked_perch", "upgrade_aquatic:cooked_pike", "turtlemancy:rabbit_stew", "twilightforest:cooked_meef", "twilightforest:cooked_venison", "twilightforest:meef_stroganoff", "twilightforest:hydra_chop", "upgrade_aquatic:cooked_lionfish", "abnormals_delight:cooked_perch_slice", "abnormals_delight:cooked_pike_slice", "wyrmroost:cooked_lowtier_meat", "wyrmroost:cooked_common_meat", "wyrmroost:cooked_apex_meat", "wyrmroost:cooked_behemoth_meat", "wyrmroost:cooked_desert_wyrm", "quark:cooked_crab_leg", "quark:cooked_frog_leg", "turtlemancy:cooked_oyster", "mysticalworld:cooked_squid", "mysticalworld:epic_squid", "mysticalworld:cooked_venison", "forbidden_arcanus:bat_soup", "forbidden_arcanus:cooked_tentacle", "farmersdelight:cooked_mutton_chops", "farmersdelight:cooked_salmon_slice", "farmersdelight:cooked_cod_slice", "farmersdelight:cooked_bacon", "farmersdelight:cooked_chicken_cuts", "farmersdelight:smoked_ham", "farmersdelight:barbeque_stick", "farmersdelight:roast_chicken", "farmersdelight:honey_glazed_ham", "farmersdelight:shepherds_pie", "undergarden:dweller_steak", "undergarden:cooked_gwibling", "undergarden:gloomper_leg", "blue_skies:cooked_grittle_flatfish", "blue_skies:cooked_municipal_monkfish", "blue_skies:cooked_charscale_moki", "blue_skies:cooked_horizofin_tunid", "blue_skies:cooked_venison", "blue_skies:cooked_carabeef", "blue_skies:cooked_monitor_tail", "farmersdelight:dog_food", "farmersdelight:beef_patty", "farmersdelight:fried_egg", "autumnity:cooked_turkey", "autumnity:cooked_turkey_piece", "theabyss_cooked_fish", "theabyss:cooked_deer_beef", "neapolitan:cooked_mint_chops"]
	#Add edible items that should be considered as raw meat. Items should also be included in 'customMeatItems'
	#Format: ["minecraft:beef", "minecraft:rabbit"]
	customRawMeatItems = ["occultism:datura", "ars_nouveau:mana_berry", "artifacts:everlasting_beef", "upgrade_aquatic:perch", "upgrade_aquatic:pike", "upgrade_aquatic:lionfish", "abnormals_delight:perch_slice", "abnormals_delight:pike_slice", "blue_skies:grittle_flatfish", "blue_skies:municipal_monkfish", "blue_skies:charscale_moki", "blue_skies:horizofin_tunid", "blue_skies:venison", "blue_skies:carabeef", "blue_skies:monitor_tail", "wyrmroost:raw_lowtier_meat", "wyrmroost:raw_common_meat", "wyrmroost:raw_apex_meat", "wyrmroost:raw_behemoth_meat", "wyrmroost:desert_wyrm", "twilightforest:raw_meef", "twilightforest:raw_venison", "undergarden:raw_dweller_meat", "undergarden:raw_gwibling", "undergarden:raw_gloomper_leg", "quark:crab_leg", "quark:frog_leg", "mysticalworld:raw_squid", "farmersdelight:mutton_chops", "farmersdelight:salmon_slice", "farmersdelight:cod_slice", "farmersdelight:bacon", "farmersdelight:chicken_cuts", "forbidden_arcanus:tentacle", "forbidden_arcanus:bat_wing", "autumnity:turkey", "autumnity:turkey_piece", "potionsmaster:bezoar", "potionsmaster:gallbladder", "farmersdelight:ham", "farmersdelight:minced_beef", "neapolitan:mint_chops"]

1.18.2:
customMeatItems = ["occultism:datura", "ars_nouveau:mana_berry", "artifacts:eternal_steak", "upgrade_aquatic:cooked_perch", "upgrade_aquatic:cooked_pike", "turtlemancy:rabbit_stew", "twilightforest:cooked_meef", "twilightforest:cooked_venison", "twilightforest:meef_stroganoff", "twilightforest:hydra_chop", "upgrade_aquatic:cooked_lionfish", "abnormals_delight:cooked_perch_slice", "abnormals_delight:cooked_pike_slice", "quark:cooked_crab_leg", "quark:cooked_frog_leg", "turtlemancy:cooked_oyster", "forbidden_arcanus:bat_soup", "forbidden_arcanus:cooked_tentacle", "farmersdelight:cooked_mutton_chops", "farmersdelight:cooked_salmon_slice", "farmersdelight:cooked_cod_slice", "farmersdelight:cooked_bacon", "farmersdelight:cooked_chicken_cuts", "farmersdelight:smoked_ham", "farmersdelight:barbeque_stick", "farmersdelight:roast_chicken", "farmersdelight:honey_glazed_ham", "farmersdelight:shepherds_pie", "undergarden:dweller_steak", "undergarden:cooked_gwibling", "undergarden:gloomper_leg", "blue_skies:cooked_grittle_flatfish", "blue_skies:cooked_municipal_monkfish", "blue_skies:cooked_charscale_moki", "blue_skies:cooked_horizofin_tunid", "blue_skies:cooked_venison", "blue_skies:cooked_carabeef", "blue_skies:cooked_monitor_tail", "farmersdelight:dog_food", "farmersdelight:beef_patty", "farmersdelight:fried_egg", "autumnity:cooked_turkey", "autumnity:cooked_turkey_piece",  "neapolitan:cooked_mint_chops", "biomemakeover:cooked_toad", "biomemakeover:cooked_glowfish", "alexsmobs:cooked_catfish", "alexsmobs:cooked_moose_ribs", "alexsmobs:cooked_lobster_tail", "alexsmobs:cooked_kangaroo_meat", "alexsdelight:cooked_kangaroo_shank", "alexsdelight:cooked_loose_moose_rib", "alexsdelight:bison_patty", "alexsdelight:cooked_bison", "alexsdelight:cooked_bunfungus", "alexsdelight:cooked_bunfungus_drumstick", "alexsdelight:cooked_catfish_slice", "alexsdelight:cooked_centipede_leg", "aquaculture:fish_fillet_cooked", "aquaculture:frog_legs_cooked", "croptopia:cooked_anchovy", "croptopia:cooked_shrimp", "croptopia:cooked_calamari", "croptopia:cooked_tuna", "croptopia:cooked_bacon", "croptopia:steamed_crab", "croptopia:crab_legs", "croptopia:steamed_clams", "croptopia:grilled_oysters", "croptopia:sausage", "croptopia:sunny_side_eggs", "croptopia:fried_frog_legs", "culturaldelights:cooked_squid", "culturaldelights:cooked_calamari", "delightful:cooked_venison_chops", "delightful:cooked_goat", "delightful:crab_rangoon", "ecologics:crab_meat", "betteranimalsplus:calamari_cooked", "betteranimalsplus:eel_meat_cooked", "betteranimalsplus:turkey_leg_cooked", "betteranimalsplus:crab_meat_cooked", "betteranimalsplus:pheasant_cooked", "betteranimalsplus:venison_cooked", "betteranimalsplus:turkey_cooked", "betteranimalsplus:fried_egg", "nethersdelight:hoglin_ear", "nethersdelight:grilled_strider", "shepherdsdelight:roast_charque", "shepherdsdelight:roast_charque_strips", "shepherdsdelight:equin_steak", "shepherdsdelight:equin_steak_chunk", "shepherdsdelight:cooked_meatloaf", "shepherdsdelight:cooked_fugu", "shepherdsdelight:cooked_fugu_cut", "shepherdsdelight:smoked_sausage", "twilightdelight:cooked_meef_slice", "twilightdelight:cooked_venison_rib"]
	#Add edible items that should be considered as raw meat. Items should also be included in 'customMeatItems'
	#Format: ["minecraft:beef", "minecraft:rabbit"]
	customRawMeatItems = ["occultism:datura", "ars_nouveau:mana_berry", "artifacts:everlasting_beef", "upgrade_aquatic:perch", "upgrade_aquatic:pike", "upgrade_aquatic:lionfish", "abnormals_delight:perch_slice", "abnormals_delight:pike_slice", "blue_skies:grittle_flatfish", "blue_skies:municipal_monkfish", "blue_skies:charscale_moki", "blue_skies:horizofin_tunid", "blue_skies:venison", "blue_skies:carabeef", "blue_skies:monitor_tail", "twilightforest:raw_meef", "twilightforest:raw_venison", "twilightforest:experiment_115", "undergarden:raw_dweller_meat", "undergarden:raw_gwibling", "undergarden:raw_gloomper_leg", "quark:crab_leg", "quark:frog_leg", "farmersdelight:mutton_chops", "farmersdelight:salmon_slice", "farmersdelight:cod_slice", "farmersdelight:bacon", "farmersdelight:chicken_cuts", "farmersdelight:ham", "farmersdelight:minced_beef", "forbidden_arcanus:tentacle", "forbidden_arcanus:bat_wing", "autumnity:turkey", "autumnity:turkey_piece", "potionsmaster:bezoar", "potionsmaster:gallbladder", "neapolitan:mint_chops", "biomemakeover:raw_toad", "aquaculture:fish_fillet_raw", "aquaculture:frog_legs_raw", "croptopia:anchovy", "croptopia:shrimp", "croptopia:calamari", "croptopia:glowing_calamari", "croptopia:tuna", "croptopia:bacon", "croptopia:crab", "croptopia:clam", "croptopia:oyster", "croptopia:frog_legs", "croptopia:sausage", "alexsmobs:raw_catfish", "alexsmobs:moose_ribs", "alexsmobs:blobfish", "alexsmobs:lobster_tail", "alexsmobs:flying_fish", "alexsmobs:kangaroo_meat", "alexsdelight:raw_bison", "alexsdelight:raw_bunfungus", "alexsdelight:raw_bunfungus_drumstick", "alexsdelight:raw_catfish_slice", "alexsdelight:kangaroo_shank", "alexsdelight:loose_moose_rib", "alexsdelight:bison_mince", "betteranimalsplus:calamari_raw", "betteranimalsplus:eel_meat_raw", "betteranimalsplus:turkey_leg_raw", "betteranimalsplus:crab_meat_raw", "betteranimalsplus:pheasant_raw", "betteranimalsplus:venison_raw", "culturaldelights:squid", "culturaldelights:glow_squid", "culturaldelights:raw_calamari", "delightful:venison_chops", "delightful:raw_goat", "nethersdelight:raw_stuffed_hoglin", "nethersdelight:ground_strider", "nethersdelight:strider_slice", "nethersdelight:hoglin_loin", "shepherdsdelight:raw_charque", "shepherdsdelight:raw_charque_strips", "shepherdsdelight:raw_equin", "shepherdsdelight:raw_equin_chunk", "shepherdsdelight:raw_meatloaf", "shepherdsdelight:ghast_tendril", "shepherdsdelight:ghast_fillet", "shepherdsdelight:cured_pufferfish", "shepherdsdelight:cure_pufferfish_cut", "shepherdsdelight:sausage", "shepherdsdelight:strider_meat_roll", "twilightdelight:raw_meef_slice", "twilightdelight:raw_venison_rib", "twilightdelight:experiment_113", "twilightdelight:experiment_110", "twilightdelight:hydra_piece"]

I'm a gourmet werewolf, what can I say

**Comment by Cheaterpaul** [comment]
Thank you for compiling this list. They will be included in the next releases
