### ISSUE TITLE
[Feature]: Config to change infection chance by player or wild werewolf attacks

### ISSUE THREAD

**Issue by AshIndigo** [TeamLapen/Werewolves#133]
### What?

Could a config option be added to prevent player infection upon getting hit by a werewolf entity or player? Maybe even as a configurable chance?

Similar to the config option that is in Vampirism itself.
![image](https://user-images.githubusercontent.com/5542898/200204043-332983b7-8761-41d3-ba4e-3125d661f792.png)

### Mod experience

I'd say it's a positive for server owners or players, the reason I'm asking this actually is because me and some others were looking to setup a 1.18.2 server and some members don't want to align themselves with any faction. And if we could say disable getting infected by wild werewolves and only get infected by the werewolf tooth that would be nice.

### Contributions

I have a modified version of this for 1.18 good to go and it should be easier enough to port to other versions. I've attached an image of the two config settings I added in the Server config

![image](https://user-images.githubusercontent.com/5542898/200345859-dd10e645-9c8c-4759-94cb-2a035f3bea32.png)

Edit: Modified suggestion to be more configurable for players as well as the config example I made

**Comment by Cheaterpaul** [comment]
Will be added and ported back :+1:
