### ISSUE TITLE
[Feature]: werevolves minions can´t put on armor

### ISSUE THREAD

**Issue by ezegamer243** [TeamLapen/Werewolves#140]
### What?

-the hunters and vampire minions can use armors (thereafter the enchantment of protection) wich makes them a lot stronger than the werevolves minions

i suppose the werevolves are bugged and cant use armor or either is a feature that is not compensated. For balance prupose the werevolves should have armor added or a boost on stats i suppose

### Mod experience

well the minions of werevolves are considerably weaker

**Comment by Cheaterpaul** [comment]
closed in 2077c6a0c74e7c4491be365c02890670caa8aed6
