### ISSUE TITLE
[Bug]: Cannot get WerewolfPlayer capability 

### ISSUE THREAD

**Issue by Dew-F** [TeamLapen/Werewolves#167]
### Minecraft Version

1.16.x

### Forge Version

36.2.39

### Vampirism Version

1.9.10

### Werewolves Version

1.1.0.3

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Spam warn single player on open local  server.

### Relevant log output

```bash
[00:34:39] [main/WARN]: Cannot get Werewolf player capability. This might break mod functionality.
java.lang.Throwable
	at de.teamlapen.werewolves.entities.player.werewolf.WerewolfPlayer.getOpt(WerewolfPlayer.java:83)
	at de.teamlapen.werewolves.entities.player.ModPlayerEventHandler.playerSize(ModPlayerEventHandler.java:214)
	at net.minecraftforge.eventbus.ASMEventHandler_1940_ModPlayerEventHandler_playerSize_Size.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$3486/896499490.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.event.ForgeEventFactory.getEntitySizeForge(ForgeEventFactory.java:760)
	at net.minecraftforge.common.extensions.IForgeEntity.getDimensionsForge(IForgeEntity.java:223)
	at net.minecraft.entity.Entity.func_213321_d(Entity.java:2404)
	at net.minecraft.entity.Entity.func_213298_c(Entity.java:1676)
	at net.minecraft.entity.player.PlayerEntity.func_213832_dB(PlayerEntity.java:363)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:265)
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70071_h_(ClientPlayerEntity.java:177)
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:193)
	at net.minecraft.client.world.ClientWorld$$Lambda$29711/1164921095.accept(Unknown Source)
	at net.minecraft.world.World.func_217390_a(World.java:554)
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:162)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1485)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:954)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$496/1531506932.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
```

### Other relevant mods

Mod List: 
		saturn-mc1.16.5-0.0.3.jar                         |Saturn                        |saturn                        |0.0.3               |DONE      |Manifest: NOSIGNATURE
		CyclopsCore-1.16.5-1.13.0.jar                     |Cyclops Core                  |cyclopscore                   |1.13.0              |DONE      |Manifest: NOSIGNATURE
		astralsorcery-1.16.5-1.14.1.jar                   |Astral Sorcery                |astralsorcery                 |1.16.4-1.14.1       |DONE      |Manifest: 45:2b:0a:49:6b:65:3b:39:a9:dd:d2:5b:55:7f:82:47:a5:1d:7a:cc:7f:a8:69:73:72:53:6f:57:4d:b2:1a:b7
		supermartijn642configlib-1.1.8-forge-mc1.16.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.8               |DONE      |Manifest: NOSIGNATURE
		aiotbotania-1.16.5-1.8.4.jar                      |AIOT Botania                  |aiotbotania                   |1.8.4               |DONE      |Manifest: NOSIGNATURE
		IntegratedTerminals-1.16.5-1.2.13.jar             |IntegratedTerminals           |integratedterminals           |1.2.13              |DONE      |Manifest: NOSIGNATURE
		Controlling-7.0.0.29.jar                          |Controlling                   |controlling                   |7.0.0.29            |DONE      |Manifest: NOSIGNATURE
		Placebo-1.16.5-4.7.1.jar                          |Placebo                       |placebo                       |4.7.1               |DONE      |Manifest: NOSIGNATURE
		modernfix-forge-5.11.1+mc1.16.5.jar               |ModernFix                     |modernfix                     |5.11.1+mc1.16.5     |DONE      |Manifest: NOSIGNATURE
		Powah-1.16.5-2.3.16.jar                           |Powah                         |powah                         |2.3.16              |DONE      |Manifest: NOSIGNATURE
		GatewaysToEternity-1.16.5-1.0.2.jar               |Gateways To Eternity          |gateways                      |1.0.2               |DONE      |Manifest: NOSIGNATURE
		randompatches-2.4.4-forge.jar                     |RandomPatches                 |randompatches                 |2.4.4-forge         |DONE      |Manifest: 92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		Apotheosis-1.16.5-4.8.9A0.jar                     |Apotheosis                    |apotheosis                    |4.8.9A0             |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.1.2.457.jar          |Mekanism: Generators          |mekanismgenerators            |10.1.2              |DONE      |Manifest: NOSIGNATURE
		FpsReducer-forge-1.24-mc1.16.5.jar                |FPS Reducer                   |fpsreducer                    |1.24-mc1.16.5       |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.16.5-0.12.1.128.jar         |Just Enough Resources         |jeresources                   |0.12.1.128          |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.16.5-4.0.870-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |DONE      |Manifest: NOSIGNATURE
		embeddium-0.2.16+mc1.16.5.jar                     |Embeddium                     |embeddium                     |0.2.16+mc1.16.5     |DONE      |Manifest: NOSIGNATURE
		entangled-1.3.16-forge-mc1.16.jar                 |Entangled                     |entangled                     |1.3.16              |DONE      |Manifest: NOSIGNATURE
		CommonCapabilities-1.16.5-2.8.0.jar               |CommonCapabilities            |commoncapabilities            |2.8.0               |DONE      |Manifest: NOSIGNATURE
		fastfurnaceminusreplacement-1.1-1.16.3.jar        |Fast Furnace Minus Replacement|fastfurnaceminusreplacement   |1.1-1.16.3          |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.477-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.477   |DONE      |Manifest: NOSIGNATURE
		MekanismAdditions-1.16.5-10.1.2.457.jar           |Mekanism: Additions           |mekanismadditions             |10.1.2              |DONE      |Manifest: NOSIGNATURE
		valkyrielib-1.16.5-3.0.9.5.jar                    |ValkyrieLib                   |valkyrielib                   |1.16.5-3.0.9.5      |DONE      |Manifest: NOSIGNATURE
		envirocore-1.16.5-3.0.9.3.jar                     |Environmental Core            |envirocore                    |1.16.5-3.0.9.3      |DONE      |Manifest: NOSIGNATURE
		envirotech-1.16.5-3.0.9.4.jar                     |Environmental Tech            |envirotech                    |1.16.5-3.0.9.4      |DONE      |Manifest: NOSIGNATURE
		Lollipop-1.16.5-3.2.9.jar                         |Lollipop                      |lollipop                      |3.2.9               |DONE      |Manifest: NOSIGNATURE
		combat_commons-0.2.0-beta-1.16.5-forge.jar        |Combat-Commons                |combat_commons                |0.2.0-beta          |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.16-forge-mc1.16.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.16              |DONE      |Manifest: NOSIGNATURE
		Botania-1.16.5-420.3.jar                          |Botania                       |botania                       |1.16.5-420.3        |DONE      |Manifest: NOSIGNATURE
		corpsecomplex-forge-1.16.5-4.0.2.8.jar            |Corpse Complex                |corpsecomplex                 |1.16.5-4.0.2.8      |DONE      |Manifest: NOSIGNATURE
		playerex-1.1.8-1.16.5.jar                         |Player Ex                     |playerex                      |1.1.8               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.1.0.0.jar                   |Curios API                    |curios                        |1.16.5-4.1.0.0      |DONE      |Manifest: NOSIGNATURE
		eidolon-0.2.7.jar                                 |Eidolon                       |eidolon                       |0.2.7               |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.3.jar                         |Patchouli                     |patchouli                     |1.16.4-53.3         |DONE      |Manifest: NOSIGNATURE
		oculus-mc1.16.5-1.4.7.jar                         |Oculus                        |oculus                        |1.4.7               |DONE      |Manifest: NOSIGNATURE
		carrotslib-mc1.16.5-3.0.jar                       |Carrots Lib                   |carrots                       |3.0                 |DONE      |Manifest: NOSIGNATURE
		IntegratedTunnels-1.16.5-1.8.11.jar               |IntegratedTunnels             |integratedtunnels             |1.8.11              |DONE      |Manifest: NOSIGNATURE
		EnigmaticLegacy-2.11.12.jar                       |Enigmatic Legacy              |enigmaticlegacy               |2.11.12             |DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.16.5-10.1.2.457.jar               |Mekanism: Tools               |mekanismtools                 |10.1.2              |DONE      |Manifest: NOSIGNATURE
		architectury-1.32.68.jar                          |Architectury                  |architectury                  |1.32.68             |DONE      |Manifest: NOSIGNATURE
		ExtraBotany-r1.2-69.jar                           |ExtraBotany                   |extrabotany                   |1.0                 |DONE      |Manifest: NOSIGNATURE
		cc-tweaked-1.16.5-1.101.3.jar                     |CC: Tweaked                   |computercraft                 |1.101.3             |DONE      |Manifest: NOSIGNATURE
		AI-Improvements-1.16.5-0.5.0.jar                  |AI-Improvements               |aiimprovements                |0.4.0               |DONE      |Manifest: NOSIGNATURE
		observerlib-1.16.5-1.5.3.jar                      |ObserverLib                   |observerlib                   |1.16.5-1.5.3        |DONE      |Manifest: NOSIGNATURE
		biomancy-forge-1.16.5-1.1.4.0.jar                 |Biomancy                      |biomancy                      |1.1.4.0             |DONE      |Manifest: NOSIGNATURE
		fastbenchminusreplacement-1.4.jar                 |FastWorkbench Minus Replacemen|fastbenchminusreplacement     |1.4                 |DONE      |Manifest: NOSIGNATURE
		enchanted-1.16.5-1.2.4.jar                        |Enchanted                     |enchanted                     |1.2.4               |DONE      |Manifest: NOSIGNATURE
		ScalingHealth-1.16.5-4.0.5+5.jar                  |Scaling Health                |scalinghealth                 |4.0.5+5             |DONE      |Manifest: NOSIGNATURE
		letmedespawn-forge-1.16-1.0.2a.jar                |Let Me Despawn                |letmedespawn                  |1.16.5-forge-1.16-1.|DONE      |Manifest: NOSIGNATURE
		CodeChickenLib-1.16.5-4.0.7.445-universal.jar     |CodeChicken Lib               |codechickenlib                |4.0.7.445           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		CBMultipart-1.16.5-3.0.4.123-universal.jar        |CBMultipart                   |cb_multipart                  |3.0.4.123           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		ProjectRed-1.16.5-4.15.0-core.jar                 |ProjectRed Core               |projectred-core               |4.15.0              |DONE      |Manifest: NOSIGNATURE
		ProjectRed-1.16.5-4.15.0-transmission.jar         |ProjectRed Transmission       |projectred-transmission       |4.15.0              |DONE      |Manifest: NOSIGNATURE
		ProjectRed-1.16.5-4.15.0-integration.jar          |ProjectRed Integration        |projectred-integration        |4.15.0              |DONE      |Manifest: NOSIGNATURE
		nutritionalbalance-1.16.5-0.7.14.jar              |Nutritional Balance           |nutritionalbalance            |1.16.5-0.7.14       |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.106.jar                 |GeckoLib                      |geckolib3                     |3.0.106             |DONE      |Manifest: NOSIGNATURE
		BetterAdvancements-1.16.5-0.1.1.115.jar           |Better Advancements           |betteradvancements            |0.1.1.115           |DONE      |Manifest: NOSIGNATURE
		rhino-forge-1605.1.5-build.75.jar                 |Rhino                         |rhino                         |1605.1.5-build.75   |DONE      |Manifest: NOSIGNATURE
		BotaniaAdditionsMC1.16.4-1.0.4.jar                |Botania Additions             |botaniaadditions              |1.0.4               |DONE      |Manifest: NOSIGNATURE
		RootsClassic-1.16.5-1.1.18.jar                    |Roots Classic                 |rootsclassic                  |1.16.5-1.1.18       |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		jei-1.16.5-7.8.0.1009.jar                         |Just Enough Items             |jei                           |7.8.0.1009          |DONE      |Manifest: NOSIGNATURE
		kubejs-forge-1605.3.19-build.299.jar              |KubeJS                        |kubejs                        |1605.3.19-build.299 |DONE      |Manifest: NOSIGNATURE
		JustEnoughCalculation-1.16.5-3.9.2.jar            |Just Enough Calculation       |jecalculation                 |3.9.2               |DONE      |Manifest: NOSIGNATURE
		AttributeFix-1.16.5-10.1.4.jar                    |AttributeFix                  |attributefix                  |10.1.4              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Mekanism-1.16.5-10.1.2.457.jar                    |Mekanism                      |mekanism                      |10.1.2              |DONE      |Manifest: NOSIGNATURE
		Clumps-6.0.0.28.jar                               |Clumps                        |clumps                        |6.0.0.28            |DONE      |Manifest: NOSIGNATURE
		Nuclearcraft-1.16-A0.3.2.jar                      |Nuclearcraft                  |nuclearcraft                  |1.16-A0.3.1         |DONE      |Manifest: NOSIGNATURE
		simplestoragenetwork-1.16.5-1.5.3.jar             |Simple Storage Network        |storagenetwork                |1.16.5-1.5.3        |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		MekanismMatter-1.20.1-Beta-1.16.5.jar             |Mekanism: Matter              |mekanismmatter                |1.19.0              |DONE      |Manifest: NOSIGNATURE
		LibX-1.16.3-1.0.76.jar                            |LibX                          |libx                          |1.16.3-1.0.76       |DONE      |Manifest: NOSIGNATURE
		compactmachines-4.0.0-beta.2.jar                  |Compact Machines 4            |compactmachines               |4.0.0-beta.2        |DONE      |Manifest: NOSIGNATURE
		pneumaticcraft-repressurized-1.16.5-2.15.12-13.jar|PneumaticCraft: Repressurized |pneumaticcraft                |1.16.5-2.15.12-13   |DONE      |Manifest: NOSIGNATURE
		lazydfu-0.1.3.jar                                 |LazyDFU                       |lazydfu                       |0.1.3               |DONE      |Manifest: NOSIGNATURE
		alib-1.16.4-1.jar                                 |A Lib                         |alib                          |1.16.4-1            |DONE      |Manifest: NOSIGNATURE
		sulfuric-1.1.jar                                  |Sulfuric                      |sulfuric                      |1.0                 |DONE      |Manifest: NOSIGNATURE
		mahoutsukai-1.16.5-v1.34.59.jar                   |Mahou Tsukai                  |mahoutsukai                   |1.16.5-v1.34.59     |DONE      |Manifest: NOSIGNATURE
		ToastControl-1.16.5-4.4.0.jar                     |Toast Control                 |toastcontrol                  |4.4.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		tl_skin_cape_forge_1.16.5-1.19.jar                |TLSkinCape                    |tlskincape                    |1.19                |DONE      |Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		BrandonsCore-1.16.5-3.0.15.248-universal.jar      |Brandon's Core                |brandonscore                  |3.0.15.248          |DONE      |Manifest: 53:bb:a0:11:bd:61:e2:1a:e2:cb:fd:f8:4f:e4:cd:a5:cc:12:f4:43:f0:78:68:3b:e1:62:c6:78:3b:27:ff:fe
		Draconic-Evolution-1.16.5-3.0.29.518-universal.jar|Draconic Evolution            |draconicevolution             |3.0.29.518          |DONE      |Manifest: 53:bb:a0:11:bd:61:e2:1a:e2:cb:fd:f8:4f:e4:cd:a5:cc:12:f4:43:f0:78:68:3b:e1:62:c6:78:3b:27:ff:fe
		Draconic-Additions-1.16.5-2.2.4.7-universal.jar   |Draconic Additions            |draconicadditions             |2.2.4.7             |DONE      |Manifest: NOSIGNATURE
		SpawnBalanceUtility-1.36.13.2.jar                 |SpawnBalanceUtility           |spawnbalanceutility           |1.36.13.2           |DONE      |Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.5-4.0.5.0.jar            |В§3Dynamic Surroundings        |dsurround                     |4.0.5.0             |DONE      |Manifest: NOSIGNATURE
		ironchest-1.16.5-11.2.21.jar                      |Iron Chests                   |ironchest                     |1.16.5-11.2.21      |DONE      |Manifest: NOSIGNATURE
		MythicBotany-1.16.5-1.4.19.jar                    |MythicBotany                  |mythicbotany                  |1.16.5-1.4.19       |DONE      |Manifest: NOSIGNATURE
		IntegratedCrafting-1.16.5-1.0.23.jar              |IntegratedCrafting            |integratedcrafting            |1.0.23              |DONE      |Manifest: NOSIGNATURE
		alchemistry-1.16.5-1.jar                          |Alchemistry                   |alchemistry                   |1.16.5-1            |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		cofh_core-1.16.5-1.5.2.22.jar                     |CoFH Core                     |cofh_core                     |1.5.2.22            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_foundation-1.16.5-1.5.2.30.jar            |Thermal Series                |thermal                       |1.5.2.30            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_expansion-1.16.5-1.5.2.16.jar             |Thermal Expansion             |thermal_expansion             |1.5.2.16            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		TConstruct-1.16.5-3.3.4.335.jar                   |Tinkers' Construct            |tconstruct                    |3.3.4.335           |DONE      |Manifest: NOSIGNATURE
		sons-of-sins-1.16.5-1.0.9.jar                     |sons of sins                  |sons_of_sins                  |1.0.9               |DONE      |Manifest: NOSIGNATURE
		integratedadditions-1.1.4.jar                     |IntegratedAdditions           |integratedadditions           |1.1.4               |DONE      |Manifest: NOSIGNATURE
		ItemPhysicLite_v1.4.8_mc1.16.5.jar                |ItemPhysic Lite               |itemphysiclite                |1.4.0               |DONE      |Manifest: NOSIGNATURE
		roughtweaks-1.16.5-2.5.1.jar                      |Rough Tweaks                  |roughtweaks                   |2.5.1               |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |Manifest: NOSIGNATURE
		mana-and-artifice-1.5.1.7.jar                     |Mana and Artifice             |mana-and-artifice             |1.5.1.7             |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.1.0-148.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.1.0-148    |DONE      |Manifest: NOSIGNATURE
		silent-lib-1.16.3-4.9.6.jar                       |Silent Lib                    |silentlib                     |4.9.6               |DONE      |Manifest: NOSIGNATURE
		jade-1.16.4-2.8.3.jar                             |Jade                          |jade                          |2.8.3               |DONE      |Manifest: NOSIGNATURE
		smoothboot-forge-1.16.4-1.2.2.jar                 |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |DONE      |Manifest: NOSIGNATURE
		ChickenChunks-1.16.5-2.9.1.89-universal.jar       |ChickenChunks                 |chickenchunks                 |2.9.1.89            |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		pipez-1.16.5-1.2.17.jar                           |Pipez                         |pipez                         |1.16.5-1.2.17       |DONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.2.5.jar                           |Flywheel                      |flywheel                      |1.16-0.2.5          |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2g.jar                       |Create                        |create                        |v0.3.2g             |DONE      |Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.157.jar                         |Mantle                        |mantle                        |1.6.157             |DONE      |Manifest: NOSIGNATURE
		xaeros_minimap_23.9.4_forge_1.16.5.jar            |Xaero's Minimap               |xaerominimap                  |23.9.4              |DONE      |Manifest: NOSIGNATURE
		IntegratedDynamics-1.16.5-1.10.15.jar             |IntegratedDynamics            |integrateddynamics            |1.10.15             |DONE      |Manifest: NOSIGNATURE
		integratednbt-1.16.4-1.4.2.jar                    |Integrated NBT                |integratednbt                 |version             |DONE      |Manifest: NOSIGNATURE
		chemlib-1.16.5-2.jar                              |Chem Lib                      |chemlib                       |1.16.5-2            |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-1.16.5-0.41.jar                   |Polymorph                     |polymorph                     |1.16.5-0.41         |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: NOSIGNATURE
		AkashicTome-1.4-16.jar                            |Akashic Tome                  |akashictome                   |1.4-16              |DONE      |Manifest: NOSIGNATURE
		FluxNetworks-1.16.5-6.2.1.14.jar                  |Flux Networks                 |fluxnetworks                  |6.2.1.14            |DONE      |Manifest: NOSIGNATURE
		performant-1.16.2-5-4.1m.jar                      |Performant                    |performant                    |3.73m               |DONE      |Manifest: NOSIGNATURE
		ToughAsNails-1.16.5-4.1.0.9-universal.jar         |Tough As Nails                |toughasnails                  |1.16.5-4.0.1.8      |DONE      |Manifest: NOSIGNATURE
		ProjectRed-1.16.5-4.15.0-expansion.jar            |ProjectRed Expansion          |projectred-expansion          |4.15.0              |DONE      |Manifest: NOSIGNATURE
		Vampirism-1.16.5-1.9.10.jar                       |Vampirism                     |vampirism                     |1.9.10              |DONE      |Manifest: NOSIGNATURE
		VampiresNeedUmbrellas-1.16.5-1.1.5.jar            |Vampires Need Umbrellas       |vampiresneedumbrellas         |1.1.5               |DONE      |Manifest: NOSIGNATURE
		Werewolves-1.16.5-1.1.0.3.jar                     |Werewolves                    |werewolves                    |1.1.0.3             |DONE      |Manifest: NOSIGNATURE
		ferritecore-2.1.1-forge.jar                       |Ferrite Core                  |ferritecore                   |2.1.1               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		occultism-1.16.5-1.29.1.jar                       |Occultism                     |occultism                     |1.16.5-1.29.1       |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v5.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v5           |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		botanicalmachinery-1.16.4-0.4.6.jar               |Botanical Machinery           |botanicalmachinery            |0.4.6               |DONE      |Manifest: NOSIGNATURE
		forestry-1.16.5-6.0.14.jar                        |Forestry                      |forestry                      |6.0.14              |DONE      |Manifest: NOSIGNATURE

**Comment by Cheaterpaul** [comment]
That will not cause a crash. This probably comes up when the player is dead and should not worry you.
