### ISSUE TITLE
[Bug]: java.lang.RuntimeException: null

### ISSUE THREAD

**Issue by LostGameDev** [TeamLapen/Werewolves#170]
### Minecraft Version

1.20.x

### Forge Version

47.2.19

### Vampirism Version

1.10.3

### Werewolves Version

1.1.0.3

### Singleplayer/Multiplayer

Singleplayer

### What happened?

When i tried to start up the game it crashed

### Relevant log output

```bash
https://pastebin.com/pSyDmV7a
```

### Reproduce steps

1.Open the game
2.Crash

**Comment by Cheaterpaul** [comment]
Duplicate of #166

**Comment by Cheaterpaul** [comment]
use the latest werewolves beta version
