### ISSUE TITLE
[Bug]: Getting negative skill points upon death

### ISSUE THREAD

**Issue by gabsdcm** [TeamLapen/Werewolves#173]
### Minecraft Version

1.20.x

### Forge Version

47.2.20

### Vampirism Version

1.10.4

### Werewolves Version

1.2.0.0

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Everytime you die as a werewolf, you get -2 skill points. I checked the configs and it doesnt seem to have a death penalty system active, so it's most likely a bug.

### Reproduce steps

1. Create a singleplayer world
2. Become a werewolf
3. Die and you will receive -2 skill points

**Comment by Eduardo2929** [comment]
I can confirm this is real. I died a few times in a multiplayer world, and I had -12 skill points. Had no other choice but to go back to level 1 :(

**Comment by Cheaterpaul** [comment]
This should be fixed by Werewolves 1.2.0.1 or 2.0.0.0-beta
