### ISSUE TITLE
[Bug]: PlayerRenderer ClassCastException

### ISSUE THREAD

**Issue by GoldenMaster8** [TeamLapen/Werewolves#178]
### Minecraft Version

1.20.x

### Forge Version

Neoforge 1.20.1-47.1.79

### Vampirism Version

1.20.1-1.10.6

### Werewolves Version

1.20.1-2.0.0.0-beta2

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Game crashes on startup

### Relevant log output

```bash
Sushi Go Crafting : https://pastebin.com/Cgq7BqgN

Industrial Foregoing : https://pastebin.com/8pj1G9Nu
```

### Reproduce steps

1. Load the game
2. It crashes

### Other relevant mods

Titanium | 3.8.25
Sushi Go Crafting | 0.5.1
Industrial Foregoing | 3.5.15

**Comment by Cheaterpaul** [comment]
This has nothing to do with Titanium, just specifically with the two mods. Same as https://github.com/TeamLapen/Werewolves/issues/177

**Comment by GoldenMaster8** [comment]
It also seems to be a problem with mekanism

[crash-2024-02-06_19.36.41-client.txt](https://github.com/TeamLapen/Werewolves/files/14187673/crash-2024-02-06_19.36.41-client.txt)
