### ISSUE TITLE
[Bug]: Not being able to eat hearts & fish; Bite death message bug.

### ISSUE THREAD

**Issue by gabsdcm** [TeamLapen/Werewolves#184]
### Minecraft Version

1.20.1

### Forge Version

47.2.20

### Vampirism Version

1.10.7

### Werewolves Version

2.0.0.0

### Singleplayer/Multiplayer

Both

### What happened?

Today I brought up two bugs I came across while playing the mod.

1. At the moment you cannot eat hearts or fish as a werewolf unless you have the "Not Meat" skill
2. There's this weird missing translation when you kill an entity (player or tamed animal) with your bite to which a "death.attack.werewolves_bite" is displayed in chat.

![Captura de tela 2024-02-17 004420](https://github.com/TeamLapen/Werewolves/assets/126027644/c569265a-7226-4eb3-8b0e-6aad24cd31d9)

**Comment by Cheaterpaul** [comment]
Thanks for reporting. Seems like didn't check that when changing the logic

**Comment by gabsdcm** [comment]
> Thanks for reporting. Seems like didn't check that when changing the logic

You're welcome fam.
Do also you know what could be causing the missing translation for the bite death message tho?

**Comment by Cheaterpaul** [comment]
Fixed that with the first commit. I added the modid to the translation id

**Comment by gabsdcm** [comment]
> Fixed that with the first commit. I added the modid to the translation id

I checked the crowdin and it has these death messages for when someone dies of bleeding. However I tested and bleeding does not kill a person, rather they will take no dmg if they're on half a heart much like poison.
