### ISSUE TITLE
[Bug]: Reincarnation into werewolf forms does not work.

### ISSUE THREAD

**Issue by DesiRe234** [TeamLapen/Werewolves#187]
### Minecraft Version

1.20.x

### Forge Version

47.2.1

### Vampirism Version

1.10.7

### Werewolves Version

2.0.0.0-beta.3

### Singleplayer/Multiplayer

Server

### What happened?

It is impossible to transform into any of the forms. There are no special conditions for transformation. On a full moon, the player also does not turn into a werewolf.

### Reproduce steps

Link to the video with the bug replay:
https://youtu.be/WSXVyVihU7E

**Comment by Cheaterpaul** [comment]
Did this work before?
Are you using a Hybrid server software?
