### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Wendyshasfallen** [TeamLapen/Werewolves#21]
## Versions
- Minecraft:  1.12.2                  
- Forge:    14.23.5.2854                
- Vampirism: 1.6.2
- Werewolves: That's the issue

- ModPack: N/A

## Issue Description
So I am getting thrown an error telling me tehnut.info cannot be called look at crash reports below with both eclipse and intellij

## Reproduce Steps
I try to build and it does not work essentially

## Additional Information
   > Could not resolve info.amerifrance.guideapi:Guide-API:1.12-2.1.6-61.
     Required by:
         project :
      > Could not resolve info.amerifrance.guideapi:Guide-API:1.12-2.1.6-61.
         > Could not get resource 'http://tehnut.info/maven/info/amerifrance/guideapi/Guide-API/1.12-2.1.6-61/Guide-API-1.12-2.1.6-61.pom'.
            > Could not GET 'http://tehnut.info/maven/info/amerifrance/guideapi/Guide-API/1.12-2.1.6-61/Guide-API-1.12-2.1.6-61.pom'.
               > tehnut.info: Name or service not known

**Comment by Cheaterpaul** [comment]
yes i know, but i only work on 1.14.

but if you want to use the 1.12 version just comment the line https://github.com/TeamLapen/Werewolves/blob/a6fc09f26ed482fae8f7fb7dc97aad20a53b57b8/gradle/forge.gradle#L41 out

**Comment by Wendyshasfallen** [comment]
Hey man thanks for the tip it worked I appreciate the help
