### ISSUE TITLE
Leveling

### ISSUE THREAD

**Issue by Cheaterpaul** [TeamLapen/Werewolves#22]
leveling as a werewolf is still an open question

**Comment by NightScale5755** [comment]
hello. Me again...
May I suggest have werewolves level based on how many animals/villagers/players they kill in Werewolf form?

**Comment by Cheaterpaul** [comment]
yes thought about that myselfe

**Comment by Cheaterpaul** [comment]
The basic leveling is implemented as followed:
- for each level you need to interact with the stone altar and supply livers and broken bones
- xp based system is there but not used atm

**Comment by Cheaterpaul** [comment]
With Werewolves 0.6 the player needs to kill a certain amount of entities to level up
