### ISSUE TITLE
Game crashes on startup with the mod Charm installed

### ISSUE THREAD

**Issue by Scapulaunit12** [TeamLapen/Werewolves#31]
If you try to launch mc with both charm and werewolves installed the game crashes. Here's the [latest.log](https://paste.ee/p/Q0cfv)

Link to mod:https://www.curseforge.com/minecraft/mc-mods/charm/files/3111048

**Comment by Cheaterpaul** [comment]
sry for the late response:

but now it is resolved
probably fixed by affe4194918614427c6e053e090734396cfa7995
