### ISSUE TITLE
server crashing when this mods in[Bug]

### ISSUE THREAD

**Issue by techteen3000** [TeamLapen/Werewolves#32]
## Versions
- Minecraft:1.16.5                    
- Forge: recent                      
- Vampirism:recent
- Werewolves:recent

- ModPack: N/A
 when the server starts up it crashes and it specificly mentions the werewolf mod when it crashes

**Comment by maxanier** [comment]
Please share the crash report otherwise there is nothing we can do.
Also "recent" is not a valid version

**Comment by Cheaterpaul** [comment]
uploaded a new version
