### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by CloWnicide** [TeamLapen/Werewolves#33]
## Versions
- Minecraft: 1.16.5
- Forge: 36.0.69
- Vampirism: 1.7.6
- Werewolves: alpha+20210217-2341

- ModPack: N/A

## Issue Description
Crash to desktop

## Reproduce Steps
Unknown

## Additional Information
Crash report: https://gist.github.com/CloWnicide/f19df1fd21ad0832bce2a8226e798321

**Comment by Cheaterpaul** [comment]
thank you for reporting,

uploaded a new version https://www.curseforge.com/minecraft/mc-mods/werewolves-become-a-beast/files/3215362

**Comment by maxanier** [comment]
@Cheaterpaul didn't you change that method yourself a couple days ago? :D
we really need to find a way to automatically preemptively warn about breaking addons or at least inform about the required addon afterwards.
