### ISSUE TITLE
[Bug] Texture missing

### ISSUE THREAD

**Issue by Gamestrust-TS** [TeamLapen/Werewolves#35]
## Versions
- Minecraft:    1.6.5           
- Forge:               1.6.5-36.0.42        
- Vampirism: Vampirism-1.16.4-1.7.6
- Werewolves: Werewolves-1.16.4-1.0.0-alpha+20210224-1336

- ModPack: N/A

## Issue Description
java.io.FileNotFoundException: werewolves:textures/actions/howling.png 
and related missing texture uploads always of the mod

werewolwevs
vampirism

**Comment by Cheaterpaul** [comment]
Yes this is just a warning that i haven't yet added the texture. But that will be done soon.
