### ISSUE TITLE
[Question] Lupus sanguinem has infinite duration

### ISSUE THREAD

**Issue by SoulZ5529** [TeamLapen/Werewolves#38]
## Versions
- Minecraft: 1.16.5                   
- Forge: 36.0.22                      
- Vampirism: Vampirism-1.16.4-1.7.7
- Werewolves: Werewolves-1.16.4-1.0.0-alpha+20210309-1957

- ModPack: N/A

## Issue Description
no modpack
none

## Reproduce Steps
 random time like 1 2 3 4 5 mins

## Additional Information
none

every time i get effected by a were wolf it have . time   . = inf

**Comment by SoulZ5529** [comment]
its . or :

**Comment by Cheaterpaul** [comment]
if you are referring to the lupus sanguinem effect, the effect is infinite an you need to sleep to become a werewolf or drink milk to get rid of it

**Comment by SoulZ5529** [comment]
> if you are referring to the lupus sanguinem effect, the effect is infinite an you need to sleep to become a werewolf or drink milk to get rid of it

o i feel stupid now thanks 😂
