### ISSUE TITLE
[Bug] Nullpointer with biomes without registryname

### ISSUE THREAD

**Issue by excusemoo1** [TeamLapen/Werewolves#40]
## Versions
- Minecraft:                  1.16.4  
- Forge:                       35.1.37
- Vampirism:
- Werewolves:

- ModPack: N/A

If youre a lvl 2 werewolf the game crashes entirely and shuts down. It put out this log (https://gist.github.com/excusemoo1/ff36b2ad38276c3c8ded835dc95aa282) 

If you become a beast at night the game suddly saves the world and shuts down

**Comment by Cheaterpaul** [comment]
In what biome does this happen? And does this also happen in vanilla biomes?

**Comment by maxanier** [comment]
@Cheaterpaul Biomes do not always have registry names. So the biome registry name is actually nullable. I think this happens with datapack based biomes

**Comment by Cheaterpaul** [comment]
uploaded a new version https://www.curseforge.com/minecraft/mc-mods/werewolves-become-a-beast/files/3270218
