### ISSUE TITLE
[Feature] Werewolf Spawnrate Config option

### ISSUE THREAD

**Issue by Suraru** [TeamLapen/Werewolves#42]
Needs option to disable ore generation for modpacks that already include silver

Also adjustable spawn rates for humans and WW

**Comment by Cheaterpaul** [comment]
Do you intent to increase or decrease the spawn rates?

**Comment by Suraru** [comment]
I wanted to decrease, make it notably rare to run into a werewolf, and possibly disable humans all together. The modpack I have is low fantasy, I plan for 1/10 players will run into a werewolf and get turned, as the current vampire spawn is about the same. 

Currently, there are groups of humans with a werewolf or two every 4 chunks, even in daylight. It's a bit overkill.

**Comment by Cheaterpaul** [comment]
i reduced the max werewolves per chunk. This should reduce the spawnrate with some additional measures. But providing a spawnrate config would change nothing. So i hope the changes are enough. Otherwise this can be changed again.
edit: ore gen option added

**Comment by Cheaterpaul** [comment]
It now has a config option
