### ISSUE TITLE
Armor textures for werewolf form don't show[Bug]

### ISSUE THREAD

**Issue by soggynutmeg** [TeamLapen/Werewolves#44]
## Versions
- Minecraft:  1.16.5                  
- Forge:   36.1.0 for 1.16.5                    
- Vampirism:   1.16.4-1.7.10
- Werewolves: 1.6.4 - 1.0.0 alpha

- ModPack: N/A

## Issue Description
   The mod works mostly as intended and it's great, there is just one issue I had and it was that the armor that's supposed to be displayed while in werewolf form doesn't show, it just has the missing textures purple and black checkered pattern. All that shows on my skin are the ears and the claws morphed into the player's hands. I still get the border around my screen in first person like I'm supposed to and normal werewolves in all forms load and look perfect, it's just when I myself am in the beast form it messes up. If this issue has already come up and there's a way to fix it, please let me know. Thank you, and have a good night :)

## Reproduce Steps
    There weren't really steps I just downloaded werewolves, vampirism, vampirism's dependancy, and then JEI, booted up the game, got infected, went to sleep, made it night, then the textures didn't load.

**Comment by Cheaterpaul** [comment]
resolved as werewolves no longer replaces the armor items
