### ISSUE TITLE
[Bug] Disable Werewolf Haven Setting Doesn't Work

### ISSUE THREAD

**Issue by Suraru** [TeamLapen/Werewolves#46]
## Versions
- Minecraft:                   1.16.5
- Forge:                       36.1.24
- Vampirism:               1.7.11
- Werewolves:          1.0.0-alpha+20210526-1539

- ModPack: BOP
-

**Comment by Cheaterpaul** [comment]
due to forge's config system this is not working at the moment, the option will be moved to common config
