### ISSUE TITLE
[Feature] New textures for werewolves

### ISSUE THREAD

**Issue by gshdg** [TeamLapen/Werewolves#50]
Can you recreate the texture model of werewolves？

**Comment by Cheaterpaul** [comment]
do you want me to recreate the whole werewolf models or just add new texture for the models?

**Comment by gshdg** [comment]
> do you want me to recreate the whole werewolf models or just add new texture for the models?

Remake the werewolf model and there is no need to do so..  You can add a lot of nice textures, preferably with different colors.  For example, white, gray, dark gray with the big gray Wolf, beast and so on

**Comment by NightScale5755** [comment]
HATE to butt in here, but I think gshdg's talking about texture variants. Like how quark does it to vanilla mobs.
Correct me if I'm wrong?

**Comment by Cheaterpaul** [comment]
yes that is currently in the works, but since i am no artist they will probably be colored variants of the existing texture
