### ISSUE TITLE
[Bug] MixinTransformerError

### ISSUE THREAD

**Issue by CanBoy67** [TeamLapen/Werewolves#52]
## Versions
- Minecraft: 1.16.5                    
- Forge: 36.1.17                      
- Vampirism: 1.8.0-beta.2
- Werewolves: 1.8-0.5.0

- ModPack: Custom Pack called Taint Mind

## Issue Description
When I go to load up the custom pack i'm working on with this mod enabled the game crashes with org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError, and the game closes

## Reproduce Steps
1. Install this mod with all dependencies
2. Wait
3. Crashes with this error

## Additional Information
[Crashlog](https://pastebin.com/peXrQKri)

**Comment by Cheaterpaul** [comment]
should not be a problem any longer with Werewolves 0.6
