### ISSUE TITLE
EXTREME lag when in beast form and 3rd person

### ISSUE THREAD

**Issue by SoImErin** [TeamLapen/Werewolves#53]
Whenever I enter beast form and go 3rd person view I get extremely low FPS and so do my friends on the server whenever I enter their render distance. I don't have Obfuscate installed. Any idea of what could cause this? Any other mod conflicts? I have 200 odd mods in the pack I'm playing.

**Comment by Cheaterpaul** [comment]
fixed by fc0c020ce56fdb2c5991f1b238ea877fe69860ce
