### ISSUE TITLE
[Bug] Werewolves do not obey Astral Sorcery's Lucerna Ritual

### ISSUE THREAD

**Issue by Lt-Bites** [TeamLapen/Werewolves#54]
## Versions
- Minecraft:   1.16.5                 
- Forge: 36.1.31                      
- Vampirism: 1.7.10
- Werewolves: 1.0.0-alpha+20210325-1916
- Astral Sorcery: 1.16.5-1.13.11

- ModPack: NA

Astral Sorcery provides a ritual that stops mobs from spawning, even in dark conditions. I believe it stops all mobs from spawning, but it might not affect peaceful mobs. It is extremely annoying as there are werewolves/humans ALL OVER my house. The issue is almost exacerbated by the fact that the ritual stops all other mobs from spawning nearby, and so werewolves/humans continue to spawn. At any time there are 5-10 werewolves in my house. 
I should note that I am a werewolf while this issue is occurring.
I should also note that my house is not entirely lit up. There are blocks that are dark enough to allow mobs to spawn, but that's what the astral sorcery ritual is for. This issue does not occur with any other mob from any other mod I have installed, so I assume it's an issue on Werewolves' side.
![Please Leave](https://user-images.githubusercontent.com/87060240/124716166-60472480-dec9-11eb-81c4-8088a60c0e52.png)

Find a spot where werewolves commonly spawn. Set up an Astral Sorcery Lucerna ritual (Use the Astral Tome if you don't know how) and you should notice that no mobs spawn except for werewolves. You can use an item called the domic resonator to see the area of influence that the ritual should have.
![Area of Effect](https://user-images.githubusercontent.com/87060240/124716127-545b6280-dec9-11eb-837d-e23c2d6851ac.png)

**Comment by Cheaterpaul** [comment]
First of all i suggest updating Werewolves to the latest version https://www.curseforge.com/minecraft/mc-mods/werewolves-become-a-beast/files/3362554 because a lot of spawning issues were fixed. This should prevent werewolves to spawn in buildings and near light sources.

Secondly Werewolves are using another `EntityClassification` that is probably not considered by Astral Sorcery.
