### ISSUE TITLE
Create zh_cn.json (Chinese translation)

### ISSUE THREAD

**Issue by gshdg** [TeamLapen/Werewolves#55]
This is a Chinese translation file of werewolf mod by me, and I hope to adopt it

The latest Chinese zh_cn
[zh_cn (2).zip](https://github.com/TeamLapen/Werewolves/files/6787970/zh_cn.2.zip)

**Comment by Cheaterpaul** [comment]
i have uploaded the translations to https://crowdin.com/project/werewolves and it will be included in the next build
