### ISSUE TITLE
[Bug] The game crushing when I starting it.

### ISSUE THREAD

**Issue by 4s-ary** [TeamLapen/Werewolves#58]
## Versions
- Minecraft: 1.16.5                    
- Forge: 36.2.0                      
- Vampirism: 1.8.0-beta5
- Werewolves: 1.0.0-alpha

- ModPack: N/A

## Issue Description
 Werewolves encountered an error during the common_setup event phase: `java.lang.NoClassDefFoundError: de/teamlapen/vampirism/potion/VampireNightVisionEffect`

## Reproduce Steps
 Idk. I just the player who like play minecraft with mods :\

## Additional Information
[crash-2021-08-25_18.47.32-fml.txt](https://github.com/TeamLapen/Werewolves/files/7048402/crash-2021-08-25_18.47.32-fml.txt)

**Comment by Cheaterpaul** [comment]
update werewolves to the latest werewolves version

**Comment by 4s-ary** [comment]
> update werewolves to the latest werewolves version

New error with latest version. Werewolves (werewolves) has failed to load currently: `java.lang.IllegalStateException: Obfuscate is not compatible with Werewolves (see log files)`

**Comment by 4s-ary** [comment]
[crash-2021-08-25_23.27.38-fml.txt](https://github.com/TeamLapen/Werewolves/files/7049761/crash-2021-08-25_23.27.38-fml.txt)

**Comment by Cheaterpaul** [comment]
"Obfuscate is not compatible with Werewolves" is pretty clear to me.

Remove Obfuscate or Werewolves
