### ISSUE TITLE
[Feature] Change werewolf form on full moon.

### ISSUE THREAD

**Issue by williamistGitHub** [TeamLapen/Werewolves#60]
## What would you like to have changed or added to Werewolves
I would like to be able to change my werewolf form on the full moon, between survival, beast, and human forms. (If they're unlocked)

## Does this make the mod experience more balanced?
Yes because I don't see why this shouldn't be added. It would just be a nice feature to have.

## Can you provide additional resources (etc. textures or models)
No.

**Comment by Cheaterpaul** [comment]
this should already be possible.

Are you using the latest version?

**Comment by williamistGitHub** [comment]
Oops, I'm not. Will update and see what happens.

**Comment by williamistGitHub** [comment]
Yup it was a version issue. I'm just an idiot for not checking which version I was on xD.
