### ISSUE TITLE
[Bug] Ticking Entity Error

### ISSUE THREAD

**Issue by hamzasarrat** [TeamLapen/Werewolves#61]
Versions
Minecraft: 1.16.5

Forge: 36.2.0

Vampirism: 1.16.5-1.8.1

Werewolves: 1.16.5-1.8-0.5.5

Issue Description
I play on a private modpack (all the mods are listed on the crash.txt) with my friends on a dedicated server. Everytime I try to level up as a werewolf with the altar, the server crashes with a ticking entity error.
This is from level 1 to level 2.

Additional Information
[crash-2021-09-20_22.58.30-server.txt](https://github.com/TeamLapen/Werewolves/files/7198726/crash-2021-09-20_22.58.30-server.txt)

**Comment by Cheaterpaul** [comment]
i think i know why it crashes.

With what item did you lit the altar? And does it also crashes when you lit the altar with a torch?

**Comment by hamzasarrat** [comment]
I used the flint and steel to initiate the ritual. I tried with a torch now, and it seems to work without crashing.

**Comment by Cheaterpaul** [comment]
then i know what it is and will be fixed.

**Comment by Cheaterpaul** [comment]
fixed with Werewolves-1.16.5-1.8-0.5.6
