### ISSUE TITLE
[Bug] WerewolfModel rendering crash with MusketMod

### ISSUE THREAD

**Issue by maxanier** [TeamLapen/Werewolves#65]
## Versions
- Minecraft: 1.16
- Vampirism: 1.8.4
- Werewolves: 1.8-0.5.6
- musketmod-1.16.5-forge-1.4.1 (latest)

- ModPack: N/A

## Issue Description
" It crash when I enter to Inventory as human-like Werevolves."

From the crash report this is an issue with Werewolf model rendering / Musketmod event handling.
https://github.com/ewewukek/mc-musketmod/blob/d5f712a3907b0f769ea40d8b0b3602b6bae16f60/src/main/java/ewewukek/musketmod/ClientSetup.java#L55

Even though the event signature does not say that the model must be a player model, but it is probably expected to be.
Even Vampirism has a similar method.

## Additional Information
https://gist.github.com/maxanier/40ef53d85e84341aff919242f7658626

**Comment by Cheaterpaul** [comment]
Fixed with Musket mod 1.4.2

**Comment by Jkj61Abn** [comment]
thx
