### ISSUE TITLE
[Bug] Huge FPS drawdowns

### ISSUE THREAD

**Issue by XionioXMaster** [TeamLapen/Werewolves#66]
## Versions
- Minecraft:       1 16 5             
- Forge:          36.2.18
             
- Vampirism: 1.8.4
- Werewolves: 1.8-0.5.6

- ModPack: N/A

## Reproduce Steps
if you activate 2 skills of the Form of the Wolf and the Form of the Beast, you can sink the nearest player up to 4 FPS from the player who turned on these abilities, a loud running sound is emitted
![image](https://user-images.githubusercontent.com/86433158/144709674-c11f897a-8a56-4bb2-8165-7bf19f95fa9b.png)
![image](https://user-images.githubusercontent.com/86433158/144709678-1c79c8d0-0d54-4675-8fae-3919ac1f8bcf.png)

## Additional Information
![image](https://user-images.githubusercontent.com/86433158/144709537-d5095b7b-6414-49a1-8bbc-f1e23f00909a.png)
![image](https://user-images.githubusercontent.com/86433158/144709584-34a8ca0b-b2f4-4056-b014-8ccf99ddbb10.png)
![image](https://user-images.githubusercontent.com/86433158/144709589-b892cbc7-7f24-4f4f-9284-edd815d657f4.png)

**Comment by DonorKrovi** [comment]
same

**Comment by NebulaticBeast** [comment]
Same.

**Comment by DragonSlayer696** [comment]
My server is also having the issue

**Comment by Ibirtem** [comment]
Same. Waiting for fix :(

**Comment by PlumWolf** [comment]
Same.

**Comment by Cheaterpaul** [comment]
Until now i am unable to reproduce this behavior.

Maybe there is another mod that produces this error. Can you share your modlists or mod packs that you use to that i can try to identify or reproduce thus behavior?

**Comment by PlumWolf** [comment]
> 

problem solved in alpha version. i dont know why. thanks for your work.

**Comment by Cheaterpaul** [comment]
If this issue still exists please reopen this issue
