### ISSUE TITLE
[Bug] Vampire Iron Golems in Werewolf controlled areas.

### ISSUE THREAD

**Issue by Tavdogg11** [TeamLapen/Werewolves#77]
## Versions
- Minecraft:  1.16.5                  
- Forge:  36.2.26                     
- Vampirism: 1.8.6
- Werewolves: 1.8-0.5.6

- ModPack: N/A

## Issue Description
Vampire iron golems keep on spawning in the werewolf controlled villages. I am unsure on what is causing this.

## Reproduce Steps
Go to a werewolf controlled base or even take over a base as a werewolf. You should see them.

## Additional Information
N/A

**Comment by Cheaterpaul** [comment]
If you are not transformed into werewolf form the iron golem does not know that you are a werewolf.

But this behavior is maybe not good. I will take a look how this can be better solved.
