### ISSUE TITLE
[Bug] Game crashes - java.lang.NullPointerException: Ticking block entity

### ISSUE THREAD

**Issue by JNCHGTR** [TeamLapen/Werewolves#80]
## Versions
- Minecraft: 1.16.5                    
- Forge: 36.2.22                      
- Vampirism: 1.8.6
- Werewolves: 1.8-0.6.0-beta.1

- ModPack: Custom

## Issue Description
Game crashes after exploring for a while.

## Reproduce Steps
N/A

## Additional Information
CRASH REPORT: https://gist.github.com/JNCHGTR/0866f5181454344b7bc1128bbef5319b

**Comment by Cheaterpaul** [comment]
fixed by c04444d983d488639b1eeb598302a50c5dd71325
