### ISSUE TITLE
I can't customize the werewolf forms when i'm not transformed and when i transform back it resets

### ISSUE THREAD

**Issue by Greatludde12** [TeamLapen/Werewolves#83]
## Versions
- Minecraft:          1.16.5          
- Forge:                       1.16.5 36.2.33
- Vampirism: 1.16.5-1.8.6
- Werewolves: 1.16.5-1.8-0.6.0

- ModPack: N/A

## Reproduce Steps

<!-- ADDITIONAL INFORMATION - 
I can't customize the werewolf forms when i'm not transformed and when i transform back it resets

**Comment by Cheaterpaul** [comment]
will be fixed in the next version
