### ISSUE TITLE
1.18.2 Crash with JEI and silver_oil

### ISSUE THREAD

**Issue by Lightfox-Lowell** [TeamLapen/Werewolves#84]
### Versions

    Minecraft: 1.18.2

    Forge: 40.0.42

    Vampirism: 1.8.2-alpha+20220402

    Werewolves: 0.6.0-alpha+20220405

    ModPack: Personal Project

### Issue Description

Silver oil causes a crash when its use is looked at in any way in JEI.

### Reproduce Steps

install 1.18.2 version of vampirsim and werewolves.

install JEI.

look up oil and right click on silver oil.

### Additional Information
[crash-2022-04-07_21.24.06-client.txt](https://github.com/TeamLapen/Werewolves/files/8448024/crash-2022-04-07_21.24.06-client.txt)

**Comment by Cheaterpaul** [comment]
will be fixed in the next version

**Comment by Cheaterpaul** [comment]
is now available in [Werewolves-1.18.2-1.8-0.6.0-alpha+20220409-1216](https://www.curseforge.com/minecraft/mc-mods/werewolves-become-a-beast/files/3741324)
