### ISSUE TITLE
[Bug]: Werewolves missing model layer.

### ISSUE THREAD

**Issue by toErIpNid** [TeamLapen/Werewolves#87]
### Minecraft Version

1.18.x

### Forge Version

40.0.44

### Vampirism Version

1.8.2-alpha+20220402-1551

### Werewolves Version

1.8-0.6.0-alpha+20220409-1216

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Modpack crashes on startup and launcher produces output below. 

### Relevant log output

```bash
https://pastebin.com/LGkHvHXr
```

### Reproduce steps

1. Run modpack.
2. Wallow in suffering as it doesn't work.

**Comment by Cheaterpaul** [comment]
Unfortunately i am not able to reproduce this behavior.

Can you check if this also occurs if you have just Vampirism + Werewolves installed ?

**Comment by Cheaterpaul** [comment]
can you try if https://www.curseforge.com/minecraft/mc-mods/werewolves-become-a-beast/files/3751524 solves this issue?

**Comment by NikFu6935** [comment]
Have the same Problem while having All the Ores installed, try out which mod is causing the Problem and send the Mod/ the Mods in here so Paul can look why they cause Problems

**Comment by Cheaterpaul** [comment]
I presume this issue to be solved with 29b84f84 and 6310847b. If this error should occur again feel free to reopen the issue
