### ISSUE TITLE
[Bug]: Server crash 1.18.2

### ISSUE THREAD

**Issue by Daihok41** [TeamLapen/Werewolves#88]
### Minecraft Version

1.18.x

### Forge Version

40.0.48

### Vampirism Version

1.18.2 -1.8.2 alpha

### Werewolves Version

1.18.2 -1.8-0.6.0

### Singleplayer/Multiplayer

Both

### What happened?

Was exploring and Server crashed, has crashed client couple times as well. Here is crash report.

https://pastebin.com/ms9GphfY

### Relevant log output

```bash
https://pastebin.com/ms9GphfY
```

### Reproduce steps

Not sure how to reproduce was just exploring world on server but has crashed in client to.

### Other relevant mods

Large modpack made by friend

**Comment by maxanier** [comment]
I assume this was triggered by a change in Vampirism  https://github.com/TeamLapen/Vampirism/commit/234049e3d0fcbd33131ad3f6f448082a556e91d3
As a workaround you can use the second latest Vampirism alpha until Werewolves is updated
https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire/files/3728569

**Comment by Daihok41** [comment]
Yup thats what i did i reverted back one until then.
