### ISSUE TITLE
[Bug]: IllegalAccessError for RenderType#create 

### ISSUE THREAD

**Issue by KubanczykT** [TeamLapen/Werewolves#89]
### Minecraft Version

1.18.x

### Forge Version

40.1.0

### Vampirism Version

alpha+20220413-2209

### Werewolves Version

alpha+20220419-1840

### Modpack

https://drive.google.com/file/d/1zSyEvOiOwqIVBC_cbQxWVqaLr4nKQ1xU/view?usp=sharing

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Well, I try to boot up the game and crash, I was adding mods to the modpack that I was making, and next up were werewolves (just to clarify, it was working without werewolves just fine), and then boom, error message in my minecraft launcher.

### Relevant log output

```bash
The game crashed whilst initializing game
Error: java.lang.IllegalAccessError: class de.teamlapen.werewolves.client.core.ModClient tried to access method 'net.minecraft.client.renderer.RenderType$CompositeRenderType net.minecraft.client.renderer.RenderType.m_173209_(java.lang.String, com.mojang.blaze3d.vertex.VertexFormat, com.mojang.blaze3d.vertex.VertexFormat$Mode, int, net.minecraft.client.renderer.RenderType$CompositeState)' (de.teamlapen.werewolves.client.core.ModClient is in module werewolves@0.6.0-alpha+20220419-1840 of loader 'TRANSFORMER' @6f8aba08; net.minecraft.client.renderer.RenderType is in module minecraft@1.18.2 of loader 'TRANSFORMER' @6f8aba08)
```

### Reproduce steps

1. Add to the mods folder Werewolves
2. Try to boot up the forge version
3. Error

### Other relevant mods

The entire list of mods is here:
https://drive.google.com/file/d/1zSyEvOiOwqIVBC_cbQxWVqaLr4nKQ1xU/view?usp=sharing
I'm not sure which one of them caused the crash with werewolves

**Comment by Cheaterpaul** [comment]
can you provide th full crash-report file?

**Comment by KubanczykT** [comment]
Uh, ok, in which folder can I find them?

**Comment by KubanczykT** [comment]
Ok, here
[crash-2022-04-19_21.26.53-client.txt](https://github.com/TeamLapen/Werewolves/files/8521861/crash-2022-04-19_21.26.53-client.txt)

**Comment by Cheaterpaul** [comment]
this is fixed in the new beta.1
