### ISSUE TITLE
Alpha Werewolf Spawners Don't Work

### ISSUE THREAD

**Issue by The13thEmpire** [TeamLapen/Werewolves#95]
Right clicking a spawner with an Alpha Werewolf Spawn Egg changes the spawner to Alpha Werewolves. However, the spawner never spawns them. I have tried varying day/night, light levels, and biomes with no results. 

MC Version: 1.16.5
Mod Version: Werewolves-1.16.5-1.8-0.6.0.jar
Mods/Modpack: All The Magic Spell Bound - ATMS (2.2.7)
Mode: Mutiplayer Dedicated Server (found same results in Single Player)

**Comment by Cheaterpaul** [comment]
Spawner are not explicitly supported by the Alpha Werewolf spawning algorithmus.

Have you tried it in the Werewolf Heaven biome above ocean level or in the dark under the sky?
