### ISSUE TITLE
[Bug]: Raw Silver has the "iron" forge tag instead of "silver"

### ISSUE THREAD

**Issue by LoSilopante** [TeamLapen/Werewolves#97]
### Minecraft Version

1.18.x

### Forge Version

40.1.19

### Vampirism Version

1.8.2-beta.1

### Werewolves Version

0.6.0-beta.3

### Singleplayer/Multiplayer

Both

### What happened?

The forge tag for raw silver is "forge:raw_materials/iron" instead of being "forge:raw_materials/silver".

The ore and processed variants of the item are tagged correctly as silver.

![example](https://user-images.githubusercontent.com/24480520/168069540-f9bcabe3-5a7e-434d-b6d7-9159f56709b5.png)

**Comment by Cheaterpaul** [comment]
Thanks, will be fixed in the next version
